### ISSUE TITLE
I know your secret!

### ISSUE THREAD

**Issue by johnjelinek** [coinbase/bittip#1]
https://github.com/coinbase/bittip/blob/master/bittip-chrome/reddit_inject.js#L78

Mwhahaha :stuck_out_tongue_closed_eyes:

**Comment by barmstrong** [comment]
Judging by your repos you probably already know this!  But it's actually unavoidable on any client side app which makes use of OAuth2.  Any iOS or Android app that makes use of OAuth for example has these embedded in the app and could be decompiled.  You could create a new OAuth 2 app and name it something similar to get a similar effect.  Let us brainstorm some ideas to mitigate this risk though.  Definitely needs some attention.

**Comment by johnjelinek** [comment]
Yes, I've been working with my WebAPI customers as well to handle this
problem. The spec recommends an embedded user-agent OR an external
verification mechanism, sorta like an external auth server that is trusted
by the app. The latter is how Azure Mobile Services handle the problem.

**Comment by TheBlueMatt** [comment]
I pushed an update which explains why this is largely a non-issue.
Tell me if I missed another attack-vector aside from just cloning the app and stealing coins using the same client_id/client_secret.
https://github.com/coinbase/bittip/blob/master/bittip-chrome/reddit_inject.js#L20

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
